language: node_js
node_js:
  - 8
  - 10
cache: yarn

script:
  - yarn lint
  - yarn stylelint
  - yarn test:cover
  - yarn prod || yarn prod # Have to run twice for scss.d.ts modules to be picked up

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false
